param([string]$ProjectRoot = "")

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
  $ProjectRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
}

$mgmtDir = Split-Path -Parent $PSScriptRoot
$mapPath = Join-Path $mgmtDir "map.json"
$map = [ordered]@{
  id = "map:$(Split-Path -Leaf $ProjectRoot)"
  type = "project-map"
  name = (Split-Path -Leaf $ProjectRoot)
  summary = "Project map generated by bootstrap script"
  root = $ProjectRoot
  updated = (Get-Date).ToString("o")
  nodes = @()
  edges = @()
  children = @()
}
$map | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $mapPath -Encoding UTF8
Write-Output "Map generated: $mapPath"
$trackerScript = Join-Path $PSScriptRoot "track-map-update.js"
if (Test-Path -LiteralPath $trackerScript) {
  $trackerResult = & node $trackerScript $ProjectRoot
  Write-Output "Tracker updated: $trackerResult"
}
